name: C/C++ CI

on:
  push:
    branches: [master, develop, testing, feature/libusb_cmake]
  pull_request:
    branches: [master, develop, testing]

jobs:
  # Linux

  job_linux_20_04_64_gcc:
    name: ubuntu-20.04 gcc
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_32_gcc:
    name: ubuntu-20.04 gcc 32-bit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-10 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_64_clang:
    name: ubuntu-20.04 clang
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-12 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_20_04_32_clang:
    name: ubuntu-20.04 clang 32-bit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-12 libusb-1.0.0-dev libgtk-3-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_64_gcc:
    name: ubuntu-22.04 gcc
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-12 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_32_gcc:
    name: ubuntu-22.04 gcc 32-bit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install gcc-12 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_64_clang:
    name: ubuntu-22.04 clang
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-14 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_linux_22_04_32_clang:
    name: ubuntu-22.04 clang 32-bit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install clang-14 libusb-1.0.0-dev libgtk-4-dev rpm
      - name: Set compiler flags
        run: |
          CFLAGS="$CFLAGS -m32"
          CXXFLAGS="$CXXFLAGS -m32"
          LDFLAGS="$LDFLAGS -m32"
      - name: make debug
        run: sudo make clean && make debug
      - name: make test
        run: sudo make clean && make test
      - name: make release
        run: sudo make clean && make release
      - name: sudo make install
        run: sudo make clean && sudo make install
      - name: sudo make package
        run: sudo make package
      - name: sudo make uninstall
        run: sudo make uninstall && sudo make clean

  job_windows_msvc:
    name: windows MSVC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: |
          mkdir build
          mkdir build\\debug
          cd build\\debug
          cmake ..\\.. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE="Debug"
          cmake --build . --target BUILD_ALL
      - name: make test
        run: |
          cd build\\debug
          rm -Recurse -Force .\\*
          cmake ..\\.. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE="Debug"
          cmake --build . --target test
      - name: make release
        run: |
          mkdir build
          mkdir build\\release
          cd build\\release
          cmake ..\\.. -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE="Release"
          cmake --build . --target BUILD_ALL
      - name: sudo make install
        run: |
          cd build\\release
          cmake --build . --target install
      - name: sudo make uninstall
        run: |
          cd build\\release
          cmake --build . --target uninstall
# Linux MinGW cross compliation

# job_linux_22_04_cross:
#   name: ubuntu-22.04 mingw64
#   runs-on: ubuntu-22.04
#   steps:
#     - uses: actions/checkout@v2
#     - name: Install dependencies
#       run: sudo apt-get install gcc-12 libusb-1.0.0-dev libgtk-4-dev rpm mingw-w64
#     - name: Building Release for Windows (x86-64) ...
#       run: sudo mkdir -p build-mingw && cd build-mingw && sudo cmake \
#         -DCMAKE_SYSTEM_NAME=Windows \
#         -DTOOLCHAIN_PREFIX=x86_64-w64-mingw32 \
#         -DCMAKE_TOOLCHAIN_FILE=$PWD/../cmake/modules/set_toolchain.cmake \
#         -DCMAKE_INSTALL_PREFIX=$PWD/install $PWD && \
#         sudo make && sudo rm -rf build-mingw && cd -
